### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by ghost** [WebCrew/TodGmbH-HumHub-Theme#1]
All inside the site seems good but once you log out, login.php seems not work. I tested this theme with a clean new HH 1.1.1 installation.

Ah, in my config guests have not access to content. Login is needed.

**Comment by WebCrew** [comment]
I use it by myself and also a friend of me with no errors so the theme is 100% working. You can check it out here: http://todgmbh.de 
The theme is using not the default HumHub login page. It is using the Login Panel in the top navigation. Take a look at the screenshot.

![screencapture-todgmbh-de-cms-dashboard-1481636123388](https://cloud.githubusercontent.com/assets/12986067/21142307/d0162568-c141-11e6-862c-c207a7954e9c.png)

Do not forget to emty or renew Your browser cache.

You wrote: _Ah, in my config guests have not access to content. Login is needed._

Note: this theme needs one space which is open also for guests, otherwise You can not see the login button :) So best is You open one Space also for guests. For example make one space with one message inside that people has to register to see all other content.
